apiVersion: v1
kind: ServiceAccount
metadata:
  name: drawtogether
  namespace: drawtogether
  labels:
    app: drawtogether
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  namespace: drawtogether
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lease-access
  namespace: drawtogether
rules:
  - apiGroups: ["akka.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "list"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-reader
  namespace: drawtogether
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: drawtogether
subjects:
  - kind: ServiceAccount
    name: drawtogether
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lease-access
  namespace: drawtogether
subjects:
  - kind: ServiceAccount
    name: drawtogether
roleRef:
  kind: Role
  name: lease-access
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-jobs
  namespace: drawtogether
subjects:
  - kind: ServiceAccount
    name: drawtogether
roleRef:
  kind: Role
  name: job-reader
  apiGroup: rbac.authorization.k8s.io
