version: 2

updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"

- package-ecosystem: "dotnet-sdk"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "wednesday"

- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
