apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This overlay demonstrates using a Deployment instead of StatefulSet
# for Akka.NET clusters with reduced rebalancing overhead during updates

namespace: drawtogether

resources:
  # Include specific base resources (not the statefulset)
  - ../../base/configs/k8s-crd.yaml
  - ../../base/configs/k8s-rbac.yaml
  - ../../base/sql-secret.yaml
  - ../../base/sql-server.yaml
  - ../../base/k8s-migrations-job.yaml
  - ../../base/ingress.yaml
  - ../../base/service.yaml
  # Use deployment instead of statefulset
  - deployment.yaml

# Apply common labels
commonLabels:
  variant: deployment

images:
  - name: drawtogether
    newTag: "0.2.11"
  - name: drawtogether-migrationservice
    newTag: "0.2.11"