apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This overlay demonstrates using a Deployment instead of StatefulSet
# for Akka.NET clusters with reduced rebalancing overhead during updates

namespace: drawtogether

resources:
  # Include the base configuration
  - ../../base
  # Add deployment instead of statefulset
  - deployment.yaml

# Remove the StatefulSet from base
patchesStrategicMerge:
  - delete-statefulset.yaml

# Apply common labels
commonLabels:
  variant: deployment

images:
  - name: drawtogether
    newTag: "0.2.11"
  - name: drawtogether-migrationservice
    newTag: "0.2.11"