apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-data
  namespace: drawtogether
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: drawtogether
spec:
  ports:
    - name: sqlserver
      port: 1644
      protocol: TCP
      targetPort: 1433
  selector:
    app: sqlserver
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: drawtogether
  labels:
    app: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlserver-secret
                key: sa-password
          - name: MSSQL_PID
            value: "Developer"
        ports:
        - containerPort: 1433
          name: sqlserver
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql/data
      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: sqlserver-data